DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE IF NOT EXISTS COMMENTS(
	DAY DATE,
	CONFLUENCE_ID VARCHAR(100),
	COUNT INTEGER,
	PRIMARY KEY(DAY, CONFLUENCE_ID),
	FOREIGN KEY(CONFLUENCE_ID) REFERENCES MEMBER(CONFLUENCE_ID)
);