DROP TABLE IF EXISTS IMAGE;

CREATE TABLE IF NOT EXISTS IMAGE(
	CONFLUENCE_ID VARCHAR(100),
	IMAGE_PATH VARCHAR(200),
	PRIMARY KEY(CONFLUENCE_ID),
	FOREIGN KEY(CONFLUENCE_ID) REFERENCES MEMBER(CONFLUENCE_ID)
);

-- HQ -- 2
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('dshin', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jooh', '');

-- PMG -- 5
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('shkwak', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('inyeung', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('judy_oh', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('yrlee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jschoi', '');

-- GT1 -- 8
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('uslee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('greatstone', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('swkim', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ajkim', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ykpark', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('dgb', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jcseok', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('yayoo', '');

-- GT2 -- 6
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jjhan', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ebkim', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jcyoo', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ehlee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ygjeon', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jhjeong', '');

-- GT3 -- 8
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('tklee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('mskim', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('ujkim', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('kch', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('gspark', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('shlee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('wurihan', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('woonghu', '');

-- GT4 -- 7
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('kcshin', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('kangsh', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jspark', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('cglee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('cjlee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('htlee', '');
INSERT INTO IMAGE(CONFLUENCE_ID, IMAGE_PATH)
VALUES ('jcg', '');