DROP TABLE IF EXISTS OVERTIME;

CREATE TABLE IF NOT EXISTS OVERTIME(
	DAY DATE,
	CONFLUENCE_ID VARCHAR(100),
	LAST_EDIT_TIME TIMESTAMP,
	OVERTIME REAL,
	PRIMARY KEY(DAY, CONFLUENCE_ID),
	FOREIGN KEY(CONFLUENCE_ID) REFERENCES MEMBER(CONFLUENCE_ID)
);